# nginx proxy address - http://172.17.0.1:8094

name: xibo
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  xibo:
    image: xibosignage/xibo-cms:latest
    pull_policy: always
    container_name: xibo-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - xibo
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8094:80"
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: xibo-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      MYSQL_HOST: xibo-db
      MYSQL_DATABASE: ${DB_CREATE_DATABASE_NAME:-xibo}
      MYSQL_USER: ${DB_USER_NAME:-xibo}
      MYSQL_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      XMR_HOST: xibo-xmr
      XMR_PUB_ADDRESS: tcp://xibo-xmr:9505
      XIBO_DEV_MODE: "false"
    volumes:
      - ./volumes/data/xibo/cms:/var/www/cms/custom
      - ./volumes/data/xibo/library:/var/www/cms/library
    depends_on:
      xibo-db:
        condition: service_healthy
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://xibo-app:80'
      - 'cloudflare.hostname=xibo.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.xibo-app.entrypoints=http'
      - 'traefik.http.routers.xibo-app-secure.tls=true'
      - 'traefik.http.routers.xibo-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.xibo-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.xibo-app.middlewares=xibo-app-https-redirect'
      - 'traefik.http.routers.xibo-app-secure.entrypoints=https'
      - 'traefik.http.routers.xibo-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.xibo-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.xibo-app-secure.service=xibo-app'
      - 'traefik.http.services.xibo-app.loadbalancer.server.port=80'

  xibo-xmr:
    image: xibosignage/xibo-xmr:latest
    pull_policy: always
    container_name: xibo-xmr
    restart: always
    logging: *default-logging
    networks:
      - xibo
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: xibo-xmr

  xibo-db:
    image: mariadb:latest
    pull_policy: always
    container_name: xibo-db
    restart: always
    logging: *default-logging
    networks:
      - xibo
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: xibo-db
      MARIADB_DATABASE: ${DB_CREATE_DATABASE_NAME:-xibo}
      MARIADB_USER: ${DB_USER_NAME:-xibo}
      MARIADB_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      MARIADB_ROOT_PASSWORD: ${DB_ADMIN_PASS:-changeme_admin_password}
    volumes:
      - ./volumes/data/db/mariadb/xibo:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  xibo:
    name: xibo
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
